//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZShopAdminServiceWClient.XYZPS
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:XYZShopAdminService")]
    [System.SerializableAttribute()]
    public partial class ProductInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InventoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductLDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductSDescField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Inventory
        {
            get
            {
                return this.InventoryField;
            }
            set
            {
                this.InventoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductImage
        {
            get
            {
                return this.ProductImageField;
            }
            set
            {
                this.ProductImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductLDesc
        {
            get
            {
                return this.ProductLDescField;
            }
            set
            {
                this.ProductLDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSDesc
        {
            get
            {
                return this.ProductSDescField;
            }
            set
            {
                this.ProductSDescField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XYZShopAdminServiceWClient.XYZPS.IProductsAdmin")]
    public interface IProductsAdmin
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsAdmin/GetAllProducts", ReplyAction="http://tempuri.org/IProductsAdmin/GetAllProductsResponse")]
        System.ComponentModel.BindingList<XYZShopAdminServiceWClient.XYZPS.ProductInfo> GetAllProducts();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IProductsAdminChannel : XYZShopAdminServiceWClient.XYZPS.IProductsAdmin, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ProductsAdminClient : System.ServiceModel.ClientBase<XYZShopAdminServiceWClient.XYZPS.IProductsAdmin>, XYZShopAdminServiceWClient.XYZPS.IProductsAdmin
    {
        
        public ProductsAdminClient()
        {
        }
        
        public ProductsAdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProductsAdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductsAdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductsAdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.ComponentModel.BindingList<XYZShopAdminServiceWClient.XYZPS.ProductInfo> GetAllProducts()
        {
            return base.Channel.GetAllProducts();
        }
    }
}
